"""Central safety bounds shared by the M6 Run and ASR services."""

MAX_RUN_UTTERANCES_PER_SESSION = 10_000
MAX_SLIDE_EVENTS_PER_SESSION = 2_000
MAX_RUN_MARKERS_PER_SESSION = 1_000
MAX_FINAL_UTTERANCE_CHARS = 4_000
MAX_PARTIAL_EVENT_CHARS = 1_200
MAX_DEBRIEF_UTTERANCES = 2_000
MAX_RUN_TRANSCRIPT_PAGE_SIZE = 200
MAX_RUN_TIMELINE_PAGE_SIZE = 200
MAX_RUN_MARKER_NOTE_CHARS = 1_000
MAX_RUN_SESSION_DURATION_MS = 12 * 60 * 60 * 1_000
MAX_ASR_AUDIO_QUEUE_FRAMES = 256
MAX_ASR_FINAL_QUEUE_SEGMENTS = 32
ASR_WORKER_JOIN_TIMEOUT_SECONDS = 30.0

# M7 Live Assist bounds. These apply to durable cue rows and the in-memory
# request window; they intentionally do not expand the M6 raw-audio limits.
MAX_LIVE_RECENT_WINDOW_MS = 15_000
MAX_LIVE_QUERY_UTTERANCES = 6
MAX_LIVE_QUERY_CHARS = 1_200
MAX_LIVE_RETRIEVAL_QUERY_CHARS = 500
MAX_EXPLICIT_QUESTION_CHARS = 1_000
MAX_LIVE_RECENT_UTTERANCES = MAX_LIVE_QUERY_UTTERANCES
MAX_LIVE_QUESTION_CHARS = MAX_LIVE_QUERY_CHARS
MAX_LIVE_CUES_PER_SESSION = 500
MAX_CUE_OFFSET = 10_000
MAX_CUE_EVIDENCE = 8
MAX_CUE_SOURCE_EXCERPT_CHARS = 800
MAX_CUE_LINE_CHARS = 180
MAX_CUE_LINES = 3
MAX_CUE_TEXT_CHARS = MAX_CUE_LINES * MAX_CUE_LINE_CHARS + (MAX_CUE_LINES - 1)
